### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by d13fa2** [marcussacana/StringReloads#13]
I'm trying to use SRL on a SoftPAL game, Bakunyuu Okami and am getting this error.
When I launch the game, it doesn't start up at all and just the command prompt shows up displaying this error.
I enabled AutoInstall and Debug in SRL.ini
```
[DBG] Hook "kernel32->LoadResource" Compiled; Hook: 0x0000000005161DB6; Bypass: 0x0000000007B10000
[ERR] [EntryPoint.cs:45(Process)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at StringReloads.Hook.Base.MemoryCodeReader.ReadByte()
   at Iced.Intel.Decoder.ReadByte()
   at Iced.Intel.Decoder.Decode(Instruction& instruction)
   at StringReloads.Hook.Base.Extensions.DecodeMany(Decoder Decoder, UInt32 MinLength)
   at StringReloads.Hook.Base.Hook.AssemblyHook()
   at StringReloads.Hook.Base.Hook.Compile(Boolean ImportHook, Nullable`1 TargetModule)
   at StringReloads.Hook.Others.EntisGLS_eslHeapAllocate.Initialize()
   at StringReloads.AutoInstall.EntisGLS..ctor()
   at StringReloads.Engine.SRL.get_Installers()
   at StringReloads.Engine.Initializer.PluginsInitializer(SRL Engine)
   at StringReloads.Engine.Initializer.Initialize(SRL Engine)
   at StringReloads.Engine.SRL.ResolveRemap(IMatch This, Char Char)
   at StringReloads.EntryPoint.Process(Void* Value)
[ERR] [Initializer.cs:28(Initialize)]
```
I already have the .lst file from LSTGenerator and I'm using SRLWrapperx86 with d3d9.dll.
Here is the full log file
[SRL.log](https://github.com/marcussacana/StringReloads/files/8664482/SRL.log)
I also tried this on Ai Kiss and have the same error.

**Comment by marcussacana** [comment]
EntisGLS it's the last new feature that I added, And Seems to be caused a bug in the SoftPal AutoInstall.
Thanks for reporint, I will take a look in some few hours in that.

**Comment by marcussacana** [comment]
I pushed an Update, test it if the bug happen in the new version.

**Comment by d13fa2** [comment]
Just tested it and it works now, thanks for the fast response
